#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;

		iif "lo" accept
		ct state established,related accept
		ct state invalid drop

		ip protocol icmp accept
		ip6 nexthdr ipv6-icmp accept

		udp sport 67 udp dport 68 accept
		udp sport 547 udp dport 546 accept

		# Podman's aardvark-dns
		iifname "podman*" udp dport 53 accept
		iifname "podman*" tcp dport 53 accept

		counter
	}

	chain forward {
		type filter hook forward priority filter; policy drop;

		ct state established,related accept
		ct state invalid drop

		# Docker and Podman bridges out, published ports in
		iifname "docker0" accept
		iifname "br-*" accept
		iifname "podman*" accept
		ct status dnat accept
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
